"""subida multiparte

Revision ID: 3f693a7c9801
Revises: b7c1d2e3f4a5
Create Date: 2026-09-27 18:00:14.505940
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '3f693a7c9801'
down_revision = 'b7c1d2e3f4a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multipart_id', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('part_size', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('part_size')
        batch_op.drop_column('multipart_id')

    # ### end Alembic commands ###
